name: CI

on:
  push:
    branches:
      - kfd16e
    paths-ignore:
      - '**/*.md'
      - 'README.md'
      - '.gitignore'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Build IPA
        run: |
          cd MiniRootFileManager15
          git apply -p1 ../submodule.patch
          cd ..
          make

      - name: Upload IPA
        uses: actions/upload-artifact@v3.1.0
        with:
          name: kfd
          path: ${{ github.workspace }}/kfd.ipa
