name: CI

on:
  push:
    branches:
      - kfd16e
    paths-ignore:
      - '**/*.md'
      - 'README.md'
      - '.gitignore'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Procursus
        uses: beerpiss/procursus-action@v2
        with:
          packages: ldid
          cache: true
          cache-path: ~/__cache

      - name: Select Xcode version (15.0)
        run: |
          sudo xcode-select -p

      - name: Build IPA
        run: |
          make

      - name: Upload IPA
        uses: actions/upload-artifact@v3.1.0
        with:
          name: kfd
          path: ${{ github.workspace }}/build/kfd.ipa
